name: Test
description: "Adding missing tests or correcting existing tests."
title: "test: "
labels: ["test"]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "List out the tests that need to be added or changed. Please also include any information as to why this was not covered in the past."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
